#!/bin/bash
java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml,javafx.web,javafx.graphics -jar /usr/share/xml-mafia/xml-mafia-1.0-SNAPSHOT-jar-with-dependencies.jar "$@"
